// lib/services/menu_ingredient_service.dart
// Service for managing menu-ingredient relationships

import '../models/menu_item_ingredient.dart';
import '../models/menu_item.dart';
import '../models/inventory.dart';

class MenuIngredientService {// Complete relationships from CSV backup (234 relationships)
  final List<MenuItemIngredient> _relations = [
    MenuItemIngredient(menuItemId: '1', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '1', inventoryId: '3'),
    MenuItemIngredient(menuItemId: '1', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '1', inventoryId: '7'),
    MenuItemIngredient(menuItemId: '1', inventoryId: '9'),
    MenuItemIngredient(menuItemId: '2', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '2', inventoryId: '2'),
    MenuItemIngredient(menuItemId: '2', inventoryId: '3'),
    MenuItemIngredient(menuItemId: '2', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '3', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '3', inventoryId: '3'),
    MenuItemIngredient(menuItemId: '3', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '4', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '4', inventoryId: '3'),
    MenuItemIngredient(menuItemId: '4', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '4', inventoryId: '7'),
    MenuItemIngredient(menuItemId: '5', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '5', inventoryId: '7'),
    MenuItemIngredient(menuItemId: '5', inventoryId: '8'),
    MenuItemIngredient(menuItemId: '6', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '6', inventoryId: '7'),
    MenuItemIngredient(menuItemId: '6', inventoryId: '13'),
    MenuItemIngredient(menuItemId: '7', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '7', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '7', inventoryId: '5'),
    MenuItemIngredient(menuItemId: '8', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '8', inventoryId: '3'),
    MenuItemIngredient(menuItemId: '8', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '9', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '9', inventoryId: '2'),
    MenuItemIngredient(menuItemId: '10', inventoryId: '11'),
    MenuItemIngredient(menuItemId: '10', inventoryId: '12'),
    MenuItemIngredient(menuItemId: '10', inventoryId: '4'),
    MenuItemIngredient(menuItemId: '11', inventoryId: '11'),
    MenuItemIngredient(menuItemId: '11', inventoryId: '13'),
    MenuItemIngredient(menuItemId: '11', inventoryId: '14'),
    MenuItemIngredient(menuItemId: '12', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '12', inventoryId: '51'),
    MenuItemIngredient(menuItemId: '13', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '14', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '15', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '16', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '17', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '18', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '12'),
    MenuItemIngredient(menuItemId: '20', inventoryId: '11'),
    MenuItemIngredient(menuItemId: '20', inventoryId: '13'),
    MenuItemIngredient(menuItemId: '21', inventoryId: '62'),
    MenuItemIngredient(menuItemId: '22', inventoryId: '63'),
    MenuItemIngredient(menuItemId: '23', inventoryId: '63'),
    MenuItemIngredient(menuItemId: '23', inventoryId: '64'),
    MenuItemIngredient(menuItemId: '24', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '24', inventoryId: '1'),
    MenuItemIngredient(menuItemId: '24', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '24', inventoryId: '59'),
    MenuItemIngredient(menuItemId: '25', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '25', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '25', inventoryId: '59'),
    MenuItemIngredient(menuItemId: '26', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '26', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '26', inventoryId: '66'),
    MenuItemIngredient(menuItemId: '26', inventoryId: '59'),
    MenuItemIngredient(menuItemId: '27', inventoryId: '67'),
    MenuItemIngredient(menuItemId: '27', inventoryId: '57'),
    MenuItemIngredient(menuItemId: '27', inventoryId: '68'),
    MenuItemIngredient(menuItemId: '28', inventoryId: '67'),
    MenuItemIngredient(menuItemId: '28', inventoryId: '57'),
    MenuItemIngredient(menuItemId: '28', inventoryId: '68'),
    MenuItemIngredient(menuItemId: '29', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '29', inventoryId: '40'),
    MenuItemIngredient(menuItemId: '30', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '30', inventoryId: '41'),
    MenuItemIngredient(menuItemId: '31', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '31', inventoryId: '39'),
    MenuItemIngredient(menuItemId: '32', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '32', inventoryId: '71'),
    MenuItemIngredient(menuItemId: '32', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '33', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '33', inventoryId: '70'),
    MenuItemIngredient(menuItemId: '33', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '34', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '34', inventoryId: '69'),
    MenuItemIngredient(menuItemId: '35', inventoryId: '65'),
    MenuItemIngredient(menuItemId: '35', inventoryId: '69'),
    MenuItemIngredient(menuItemId: '35', inventoryId: '37'),
    MenuItemIngredient(menuItemId: '36', inventoryId: '58'),
    MenuItemIngredient(menuItemId: '36', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '36', inventoryId: '59'),
    MenuItemIngredient(menuItemId: '37', inventoryId: '58'),
    MenuItemIngredient(menuItemId: '37', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '37', inventoryId: '59'),
    MenuItemIngredient(menuItemId: '38', inventoryId: '58'),
    MenuItemIngredient(menuItemId: '38', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '38', inventoryId: '6'),
    MenuItemIngredient(menuItemId: '39', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '40', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '41', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '42', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '43', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '43', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '44', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '44', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '45', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '45', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '46', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '46', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '47', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '47', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '47', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '48', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '48', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '48', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '49', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '49', inventoryId: '22'),
    MenuItemIngredient(menuItemId: '49', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '50', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '50', inventoryId: '22'),
    MenuItemIngredient(menuItemId: '50', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '51', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '51', inventoryId: '27'),
    MenuItemIngredient(menuItemId: '51', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '52', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '52', inventoryId: '27'),
    MenuItemIngredient(menuItemId: '52', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '53', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '53', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '53', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '54', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '54', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '54', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '55', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '55', inventoryId: '30'),
    MenuItemIngredient(menuItemId: '56', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '56', inventoryId: '30'),
    MenuItemIngredient(menuItemId: '57', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '57', inventoryId: '37'),
    MenuItemIngredient(menuItemId: '57', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '58', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '58', inventoryId: '26'),
    MenuItemIngredient(menuItemId: '58', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '59', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '59', inventoryId: '26'),
    MenuItemIngredient(menuItemId: '59', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '60', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '60', inventoryId: '76'),
    MenuItemIngredient(menuItemId: '60', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '11', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '13', inventoryId: '52'),
    MenuItemIngredient(menuItemId: '13', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '14', inventoryId: '53'),
    MenuItemIngredient(menuItemId: '14', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '15', inventoryId: '54'),
    MenuItemIngredient(menuItemId: '15', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '16', inventoryId: '55'),
    MenuItemIngredient(menuItemId: '16', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '17', inventoryId: '56'),
    MenuItemIngredient(menuItemId: '17', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '18', inventoryId: '57'),
    MenuItemIngredient(menuItemId: '18', inventoryId: '50'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '60'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '61'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '57'),
    MenuItemIngredient(menuItemId: '19', inventoryId: '58'),
    MenuItemIngredient(menuItemId: '61', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '61', inventoryId: '75'),
    MenuItemIngredient(menuItemId: '62', inventoryId: '24'),
    MenuItemIngredient(menuItemId: '62', inventoryId: '75'),
    MenuItemIngredient(menuItemId: '63', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '63', inventoryId: '75'),
    MenuItemIngredient(menuItemId: '64', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '64', inventoryId: '75'),
    MenuItemIngredient(menuItemId: '65', inventoryId: '39'),
    MenuItemIngredient(menuItemId: '65', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '66', inventoryId: '41'),
    MenuItemIngredient(menuItemId: '66', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '67', inventoryId: '40'),
    MenuItemIngredient(menuItemId: '67', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '68', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '68', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '69', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '69', inventoryId: '37'),
    MenuItemIngredient(menuItemId: '69', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '70', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '70', inventoryId: '22'),
    MenuItemIngredient(menuItemId: '70', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '71', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '71', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '71', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '72', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '72', inventoryId: '37'),
    MenuItemIngredient(menuItemId: '72', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '73', inventoryId: '29'),
    MenuItemIngredient(menuItemId: '73', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '73', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '74', inventoryId: '75'),
    MenuItemIngredient(menuItemId: '75', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '75', inventoryId: '31'),
    MenuItemIngredient(menuItemId: '76', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '76', inventoryId: '32'),
    MenuItemIngredient(menuItemId: '77', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '77', inventoryId: '39'),
    MenuItemIngredient(menuItemId: '78', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '78', inventoryId: '74'),
    MenuItemIngredient(menuItemId: '79', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '79', inventoryId: '24'),
    MenuItemIngredient(menuItemId: '80', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '80', inventoryId: '22'),
    MenuItemIngredient(menuItemId: '81', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '81', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '82', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '82', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '83', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '83', inventoryId: '37'),
    MenuItemIngredient(menuItemId: '84', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '84', inventoryId: '25'),
    MenuItemIngredient(menuItemId: '84', inventoryId: '31'),
    MenuItemIngredient(menuItemId: '85', inventoryId: '28'),
    MenuItemIngredient(menuItemId: '85', inventoryId: '23'),
    MenuItemIngredient(menuItemId: '86', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '86', inventoryId: '33'),
    MenuItemIngredient(menuItemId: '87', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '87', inventoryId: '34'),
    MenuItemIngredient(menuItemId: '88', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '88', inventoryId: '35'),
    MenuItemIngredient(menuItemId: '89', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '89', inventoryId: '31'),
    MenuItemIngredient(menuItemId: '90', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '90', inventoryId: '32'),
    MenuItemIngredient(menuItemId: '91', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '91', inventoryId: '36'),
    MenuItemIngredient(menuItemId: '92', inventoryId: '72'),
    MenuItemIngredient(menuItemId: '92', inventoryId: '73'),
  ];

  List<MenuItemIngredient> get menuItemIngredients => _relations;

  List<String> getIngredientIdsForMenuItem(String menuItemId) {
    return _relations
      .where((rel) => rel.menuItemId == menuItemId)
      .map((rel) => rel.inventoryId)
      .toList();
  }

  List<String> getMenuItemsUsingIngredient(String inventoryId) {
    return _relations
      .where((rel) => rel.inventoryId == inventoryId)
      .map((rel) => rel.menuItemId)
      .toList();
  }

  bool validateRelationships(List<MenuItem> menuItems, List<Inventory> inventoryItems) {
    final menuItemIds = menuItems.map((item) => item.id.toString()).toSet();
    final inventoryIds = inventoryItems.map((item) => item.id).toSet();

    for (final relation in _relations) {
      if (!menuItemIds.contains(relation.menuItemId) || !inventoryIds.contains(relation.inventoryId)) {
        return false;
      }
    }    return true;
  }
}
